name: Gradle Build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        java: [ "25" ]
        distribution: [ "temurin" ]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v6.0.2
      - name: Set up JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: "gradle"
          check-latest: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME